name: configes_abdellali_pro

description: CONFIGES ABDELLALI PRO

publish_to: "none"

version: 1.0.0+1


environment:
  sdk: ">=3.0.0 <4.0.0"



dependencies:

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8


  # API
  http: ^1.2.2


  # Open links
  url_launcher: ^6.3.1


  # Pick files
  file_picker: ^8.1.2


  # Share .abde files
  share_plus: ^10.0.2


  # Encryption
  crypto: ^3.0.5



dev_dependencies:

  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



flutter:

  uses-material-design: true


  assets:

    - assets/images/
