name: configes_abdellali_pro
description: A professional config manager application
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Core
  cupertino_icons: ^1.0.6
  
  # File & Storage
  file_picker: ^6.1.1
  path_provider: ^2.1.0
  share_plus: ^7.2.1
  
  # Encryption
  pointycastle: ^3.7.3
  crypto: ^3.0.3
  
  # Other
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
